// Auth-related schemas (generated by Better Auth CLI)
export * from "./auth";

// You can also create namespace exports for better organization:
// import * as authSchemas from "./auth";
// import * as appSchemas from "./app";
// export { authSchemas, appSchemas };
